### ISSUE TITLE
Numbers or strings?

### ISSUE THREAD

**Issue by alan-schwarzenberger** [ghoneycutt/puppet-module-nscd#45]
The documentation is a little vague on numeric settings such as hosts_negative_time_to_live. That says the default is 20, whereas other settings have numbers single quoted into strings.
If you actually use a number (eg in hiera nscd::hosts_negative_time_to_live: 0) then for me (Puppet 4.3.2 and Puppet Server 2.2.0 with Stdlib 4.12.0) a Puppet compile time error results as the first parameter to validate_re must be a string.
I could help do a PR, but some guidance first on your preference please: update the documentation to be clear that all parameters must be strings, or change the code by quoting all first parameters to validate_re to force stringification? I can't spot anything else in the code that would cause a problem if these were numbers.

**Comment by ghoneycutt** [comment]
Thank you for reporting this!

The docs read that all numbers should be cast as strings. Looking through the code, this is needed because we are doing validate_re() on them.

Could you please send me a PR that fixes the examples in the documentation by putting single quotes around the numbers that should be shown as strings?

**Comment by alan-schwarzenberger** [comment]
Sorry for the delay. See #47

**Comment by ghoneycutt** [comment]
Released in v1.9.1

Thank you very much!
